language: node_js
node_js: stable
cache: npm
before_install:
- openssl aes-256-cbc -K $encrypted_42cd25acbd0a_key -iv $encrypted_42cd25acbd0a_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
install:
- npm i
script:
- npm run build
after_success:
- rsync -P -rv --delete -e 'ssh -o stricthostkeychecking=no' dist/
  $REMOTE_USER@$REMOTE_IP:~/static
